Ajay Giri
Roll No. :13204

In [1]:
import numpy as np

In [4]:
x = np.array([3, 4, 7, 9, 10])

In [5]:
print(x)

[ 3  4  7  9 10]


In [6]:
type(x)

numpy.ndarray

In [8]:
x=np.array(([3, 4, 7, 9, 10]),dtype="float")

In [9]:
type(x)

numpy.ndarray

In [20]:
x = np.zeros((3, 4))

In [21]:
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
x=np.ones((3,4))

In [13]:
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [14]:
x=np.eye(3,3)

In [15]:
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
x = np.full((3, 4), 7)

In [24]:
print(x)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [25]:
x=np.eye(3,3)

In [26]:
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [28]:
x = np.arange(3, 10, 4)

print(x)

In [30]:
x = np.linspace(7, 10, 10)

In [31]:
print(x)

[ 7.          7.33333333  7.66666667  8.          8.33333333  8.66666667
  9.          9.33333333  9.66666667 10.        ]
